apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-app-ingress
  namespace: counter-app
spec:
  ingressClassName: nginx
  rules:
  - host: counter-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: laravel-app
            port:
              number: 80
