apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: counter-app
type: Opaque
stringData:
  APP_KEY: "base64:UO59F6dtV/TQDoOkMAsU+vw+MGP5VBjTj+sdPEkqw9c="
  DB_PASSWORD: "app_password"
  DB_ROOT_PASSWORD: "app_root_password"
